// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqJ07I9eRChAxy9md5nYPBuM-qlRN9j_s',
    appId: '1:489164787450:web:0c17f2cea2d5ca2752c343',
    messagingSenderId: '489164787450',
    projectId: 'flutter-assessment-acd86',
    authDomain: 'flutter-assessment-acd86.firebaseapp.com',
    storageBucket: 'flutter-assessment-acd86.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIN86p5pEdHrq6JNP5A6kGPIbvE8N0rwE',
    appId: '1:489164787450:android:58ed58afb83c925852c343',
    messagingSenderId: '489164787450',
    projectId: 'flutter-assessment-acd86',
    storageBucket: 'flutter-assessment-acd86.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3EgFM9yRw-5PRb3kXE5NSCxILi2AUuZc',
    appId: '1:489164787450:ios:e36d5dcafcf7a7af52c343',
    messagingSenderId: '489164787450',
    projectId: 'flutter-assessment-acd86',
    storageBucket: 'flutter-assessment-acd86.appspot.com',
    iosBundleId: 'com.example.appAssesment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3EgFM9yRw-5PRb3kXE5NSCxILi2AUuZc',
    appId: '1:489164787450:ios:e36d5dcafcf7a7af52c343',
    messagingSenderId: '489164787450',
    projectId: 'flutter-assessment-acd86',
    storageBucket: 'flutter-assessment-acd86.appspot.com',
    iosBundleId: 'com.example.appAssesment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqJ07I9eRChAxy9md5nYPBuM-qlRN9j_s',
    appId: '1:489164787450:web:f9e6b0882de02fd552c343',
    messagingSenderId: '489164787450',
    projectId: 'flutter-assessment-acd86',
    authDomain: 'flutter-assessment-acd86.firebaseapp.com',
    storageBucket: 'flutter-assessment-acd86.appspot.com',
  );
}
